In [1]:
import torch

In [2]:
# simple operation rehash
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


In [3]:
# broadcasting rules
a =     torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.9672, 0.6612],
         [0.2161, 0.7842],
         [0.1996, 0.3523]],

        [[0.9672, 0.6612],
         [0.2161, 0.7842],
         [0.1996, 0.3523]],

        [[0.9672, 0.6612],
         [0.2161, 0.7842],
         [0.1996, 0.3523]],

        [[0.9672, 0.6612],
         [0.2161, 0.7842],
         [0.1996, 0.3523]]])


In [4]:
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.0196, 0.0196],
         [0.3533, 0.3533],
         [0.9691, 0.9691]],

        [[0.0196, 0.0196],
         [0.3533, 0.3533],
         [0.9691, 0.9691]],

        [[0.0196, 0.0196],
         [0.3533, 0.3533],
         [0.9691, 0.9691]],

        [[0.0196, 0.0196],
         [0.3533, 0.3533],
         [0.9691, 0.9691]]])


In [5]:
d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.6008, 0.4497],
         [0.6008, 0.4497],
         [0.6008, 0.4497]],

        [[0.6008, 0.4497],
         [0.6008, 0.4497],
         [0.6008, 0.4497]],

        [[0.6008, 0.4497],
         [0.6008, 0.4497],
         [0.6008, 0.4497]],

        [[0.6008, 0.4497],
         [0.6008, 0.4497],
         [0.6008, 0.4497]]])


In [6]:
# switch between ndarrays and PyTorch tensors
import numpy as np
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# reverse example of converting from PyTorch tensor into ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.9588, 0.0217, 0.7683],
        [0.2048, 0.8482, 0.2078]])
[[0.95882124 0.02166641 0.7683494 ]
 [0.20484549 0.84816504 0.20775098]]


In [8]:
# using the same underlying memory
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.95882124  0.02166641  0.7683494 ]
 [ 0.20484549 17.          0.20775098]]
