In [1]:
# require gradient on a variable

In [2]:
import torch
from torch.autograd import Variable

In [3]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

tensor([-0.3799,  2.2665,  0.0942], requires_grad=True)


In [4]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-194.5070, 1160.4614,   48.2542], grad_fn=<MulBackward0>)


In [5]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

In [6]:
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [7]:
# Fronzen parameters

In [8]:
from torch import nn, optim
import torchvision

In [9]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [10]:
model = torchvision.models.resnet18(pretrained=True)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 105MB/s]


In [11]:
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [12]:
model.fc = nn.Linear(512, 10)

In [13]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [14]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)
