# Tensors

In [2]:
import torch

## zeros()

In [3]:
# For getting a tensor filled with scalar value of 0's specify the dimensions
w = torch.zeros(4, 3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [4]:
w.size()

torch.Size([4, 3])

In [5]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [6]:
# in a neural networks we start with random weights
w = torch.randn(4,3) # ran for random, n for normal distribution
w

tensor([[ 0.9421,  0.1399, -0.3639],
        [-0.8317,  0.3643,  0.3980],
        [ 0.7012, -2.0033,  0.0787],
        [-0.1672, -0.9575,  0.7159]])

In [7]:
t = torch.randn_like(w) # here mentioned w for passing the dimensions
t

tensor([[ 1.5503, -0.7232, -0.7303],
        [ 0.8991,  0.6926, -1.3534],
        [-1.1470, -0.2282, -0.3637],
        [ 0.8813,  0.0577,  0.7503]])

## fill_()

In [8]:
w.fill_(1) # Fills the tensor with 1's

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [10]:
# For reshaping a tensor use the view
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# without calculating to create a new tensor and let the pytorch to decide
t = w.view(3, -1)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [13]:
# For converting the tensor to a numpy array
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
# For conforming that is a numpy array
type(w.numpy())

numpy.ndarray