# Autograd with tensors

In [1]:
import torch

In [2]:
# To keep track of operations on a tensor, make requires_grad = True
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[ 1.4193,  2.0523, -0.3667],
        [ 0.7994,  0.6210, -0.8814],
        [ 0.3889,  1.4141,  0.3395],
        [ 0.5259,  0.5030, -1.2145]], requires_grad=True)

In [4]:
# Set it false
w.requires_grad_(False)
w

tensor([[ 1.4193,  2.0523, -0.3667],
        [ 0.7994,  0.6210, -0.8814],
        [ 0.3889,  1.4141,  0.3395],
        [ 0.5259,  0.5030, -1.2145]])

In [5]:
# Turn it true
w.requires_grad_(True)

tensor([[ 1.4193,  2.0523, -0.3667],
        [ 0.7994,  0.6210, -0.8814],
        [ 0.3889,  1.4141,  0.3395],
        [ 0.5259,  0.5030, -1.2145]], requires_grad=True)

In [6]:
# Crreate a new tensor y
y = torch.exp(w)
print(y)

tensor([[4.1342, 7.7860, 0.6931],
        [2.2242, 1.8608, 0.4142],
        [1.4753, 4.1129, 1.4042],
        [1.6920, 1.6537, 0.2969]], grad_fn=<ExpBackward0>)


In [7]:
# print the gradent function of y
print(y.grad_fn)

In [8]:
# create another tensor
outp = y.mean()
print(outp)

tensor(2.3123, grad_fn=<MeanBackward0>)


In [9]:
# we dont have gradients for 'w'
print(w.grad)

None


In [10]:
# Running the backward
outp.backward()

In [11]:
# Print the values of the gradients for W
print(w.grad)

tensor([[0.3445, 0.6488, 0.0578],
        [0.1854, 0.1551, 0.0345],
        [0.1229, 0.3427, 0.1170],
        [0.1410, 0.1378, 0.0247]])


In [12]:
# To stop a tensor from tracking a history, we can use the detach method
print(w.detach())

tensor([[ 1.4193,  2.0523, -0.3667],
        [ 0.7994,  0.6210, -0.8814],
        [ 0.3889,  1.4141,  0.3395],
        [ 0.5259,  0.5030, -1.2145]])


In [ ]:
print(outp.requires_grad)

with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

True
False
